---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.debug:
        msg: loading playbook

    - name: This fails because I'm inside a play already
      ansible.builtin.import_playbook: ../../security-group.yml